server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admin_db?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    change-log: classpath:config/liquibase/master.yaml